#pragma once

#define DRV_EN_DDR DDRB
#define DRV_EN_PIN PORTB1
#define DRV_EN_PORT PORTB

#define DRV_M0_DDR DDRB
#define DRV_M0_PIN PORTB0
#define DRV_M0_PORT PORTB

#define DRV_M1_DDR DDRD
#define DRV_M1_PIN PORTD7
#define DRV_M1_PORT PORTD

#define DRV_M2_DDR DDRD
#define DRV_M2_PIN PORTD6
#define DRV_M2_PORT PORTD

#define DRV_DIR_DDR DDRD
#define DRV_DIR_PIN PORTD4
#define DRV_DIR_PORT PORTD

#define DRV_STEP_DDR DDRD
#define DRV_STEP_PIN PORTD5
#define DRV_STEP_PORT PORTD

#define LED_DDR DDRD
#define LED_PIN PORTD2
#define LED_PORT PORTD
